name: benchsets
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults
dependencies:
  - python>=3.8
  - pandas==1.1.3
  - seaborn=0.11.0
  - sourmash>=4,<5
  - notebook>=6,<7
  - jupyterlab
  - plotly>=4.10.0,<5
  - plotly:python-kaleido
  - ipywidgets>=7.5
  - ipykernel
  - pip
  - pip:
    - dendropy==4.4.0
